name: Github Action CICD Pipeline example

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4