name: Github Action CICD Pipeline example

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin JDK
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml                  